kind: pipeline
type: docker
name: CI & Quality Check (Java/Gradle)

workspace:
  base: /usr/src
  path: app

steps:
  - name: cache
    image: plugins/cache:2
    settings:
      restore: true
      rebuild: true
      mount:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
      repo: bacal
      keys:
        - gradle-{{ checksum "build.gradle" }}
        - gradle-latest

  - name: build_and_test
    image: gradle:7.6-jdk17
    commands:
      - echo "Building with Gradle..."
      - ./gradlew build --no-daemon
      - echo "Running tests..."
      - ./gradlew test

  - name: generate_coverage_report
    image: gradle:7.6-jdk17
    commands:
      - echo "Generating Jacoco report..."
      - ./gradlew jacocoTestReport

  - name: upload_coverage_codacy
    image: alpine/curl:latest
    environment:
      CODACY_PROJECT_TOKEN:
        from_secret: CODACY_PROJECT_TOKEN
    commands:
      - echo "Uploading coverage to Codacy..."
      - curl -X POST -H 'Content-Type: application/json' --data '{"token":"$$CODACY_PROJECT_TOKEN","commit":"$$DRONE_COMMIT_SHA", "coverageReports":["build/reports/jacoco/test/jacocoTestReport.xml"]}' https://api.codacy.com/api/v3/coverage/upload

  - name: sonarqube_analysis
    image: gradle:7.6-jdk17
    environment:
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
    commands:
      - echo "Running SonarQube analysis..."
      - ./gradlew sonarqube -Dsonar.login=$$SONAR_TOKEN
